[project]
name = "analysis"
version = "0.1.0"

dependencies = [
    "pandas",
    "numpy",
    "scipy",
    "scikit-learn",
    "polars",
    "pyarrow",
    "ipykernel",
    "jupyterlab",
    "matplotlib",
    "matplotlib-fontja",
    "seaborn>=0.13",
    "openpyxl",
    "statsmodels",
]