[project]
name = "analysis"
version = "0.1.0"

dependencies = [
  "pandas",
  "numpy",
  "scikit-learn",
  "polars",
  "ipykernel",
  "matplotlib",
  "matplotlib-fontja",
  "seaborn",
  "openpyxl",
  "scipy",
]